# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-12 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_user_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
